In [1]:
from pprint import pprint
import pandas as pd
import numpy as np

# Loading data

In [2]:
data = pd.read_csv('HW1-data.csv')

display(data)

,User,"Gender (1 =F, 0=M)",260: Star Wars: Episode IV - A New Hope (1977),1210: Star Wars: Episode VI - Return of the Jedi (1983),356: Forrest Gump (1994),"318: Shawshank Redemption, The (1994)","593: Silence of the Lambs, The (1991)",3578: Gladiator (2000),1: Toy Story (1995),2028: Saving Private Ryan (1998),...,2396: Shakespeare in Love (1998),2916: Total Recall (1990),780: Independence Day (ID4) (1996),541: Blade Runner (1982),1265: Groundhog Day (1993),"2571: Matrix, The (1999)",527: Schindler's List (1993),"2762: Sixth Sense, The (1999)",1198: Raiders of the Lost Ark (1981),34: Babe (1995)
0,755,0,1.0,5.0,2.0,NaN,4.0,4.0,2.0,2.0,...,2.0,NaN,5.0,2.0,NaN,4.0,2.0,5.0,NaN,NaN
1,5277,0,5.0,3.0,NaN,2.0,4.0,2.0,1.0,NaN,...,3.0,2.0,2.0,NaN,2.0,NaN,5.0,1.0,3.0,NaN
2,1577,1,NaN,NaN,NaN,5.0,2.0,NaN,4.0,NaN,...,NaN,1.0,4.0,4.0,1.0,1.0,2.0,3.0,1.0,3.0
3,4388,0,NaN,3.0,NaN,NaN,NaN,1.0,2.0,3.0,...,NaN,4.0,1.0,3.0,5.0,NaN,5.0,1.0,1.0,2.0
4,1202,1,4.0,3.0,4.0,1.0,4.0,1.0,NaN,4.0,...,5.0,1.0,NaN,4.0,NaN,3.0,5.0,5.0,NaN,NaN
5,3823,1,2.0,4.0,4.0,4.0,NaN,NaN,3.0,1.0,...,5.0,2.0,4.0,NaN,1.0,NaN,NaN,3.0,NaN,2.0
6,5448,0,NaN,NaN,3.0,1.0,1.0,4.0,NaN,5.0,...,1.0,NaN,NaN,3.0,NaN,1.0,NaN,NaN,5.0,2.0
7,5347,0,4.0,NaN,NaN,NaN,3.0,2.0,2.0,NaN,...,NaN,2.0,3.0,2.0,4.0,NaN,1.0,3.0,5.0,NaN
8,4117,1,5.0,1.0,NaN,4.0,2.0,4.0,4.0,4.0,...,2.0,3.0,1.0,NaN,5.0,NaN,NaN,NaN,NaN,5.0
9,2765,0,4.0,2.0,NaN,5.0,3.0,NaN,4.0,3.0,...,NaN,NaN,2.0,NaN,NaN,2.0,5.0,1.0,NaN,NaN
10,5450,1,2.0,1.0,5.0,NaN,NaN,5.0,5.0,NaN,...,NaN,3.0,2.0,NaN,NaN,1.0,NaN,2.0,1.0,4.0
11,139,0,3.0,5.0,2.0,NaN,2.0,NaN,2.0,NaN,...,3.0,NaN,3.0,NaN,2.0,5.0,NaN,NaN,NaN,2.0
12,1940,0,2.0,3.0,NaN,5.0,4.0,NaN,4.0,5.0,...,NaN,2.0,4.0,NaN,3.0,NaN,NaN,NaN,5.0,NaN
13,3118,1,3.0,NaN,3.0,NaN,2.0,NaN,3.0,NaN,...,NaN,1.0,2.0,2.0,3.0,5.0,1.0,NaN,NaN,NaN
14,4656,1,4.0,4.0,NaN,NaN,5.0,5.0,2.0,NaN,...,NaN,1.0,3.0,NaN,2.0,NaN,3.0,NaN,3.0,1.0
15,4796,1,NaN,NaN,1.0,NaN,3.0,2.0,NaN,2.0,...,5.0,NaN,NaN,NaN,5.0,2.0,2.0,4.0,3.0,4.0
16,6037,0,NaN,NaN,NaN,NaN,4.0,NaN,2.0,NaN,...,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
17,3048,1,4.0,5.0,1.0,5.0,1.0,1.0,4.0,NaN,...,NaN,NaN,NaN,4.0,NaN,NaN,2.0,1.0,2.0,5.0
18,4790,0,5.0,1.0,NaN,NaN,NaN,4.0,2.0,1.0,...,3.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN
19,4489,0,1.0,2.0,2.0,4.0,5.0,NaN,2.0,3.0,...,1.0,NaN,NaN,5.0,5.0,4.0,3.0,5.0,3.0,NaN

# Mean calculation

Calculate the mean rating for each movie, order with the highest rating listed first.

In [3]:
mean_ratings = dict(data.iloc[:,2:].mean())

mean_ratings_sorted = {k: round(v, 3) for k, v in sorted(mean_ratings.items(),
                                                         key=lambda item: item[1],
                                                         reverse=True)}

pprint(mean_ratings_sorted, sort_dicts=False)

{'318: Shawshank Redemption, The (1994)': 3.6,
 '260: Star Wars: Episode IV - A New Hope (1977)': 3.267,
 '541: Blade Runner (1982)': 3.222,
 '1265: Groundhog Day (1993)': 3.167,
 '593: Silence of the Lambs, The (1991)': 3.062,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 3.0,
 '2028: Saving Private Ryan (1998)': 3.0,
 '296: Pulp Fiction (1994)': 3.0,
 "527: Schindler's List (1993)": 3.0,
 '34: Babe (1995)': 3.0,
 '3578: Gladiator (2000)': 2.917,
 '2396: Shakespeare in Love (1998)': 2.909,
 '1198: Raiders of the Lost Ark (1981)': 2.909,
 '2571: Matrix, The (1999)': 2.833,
 '2762: Sixth Sense, The (1999)': 2.833,
 '1: Toy Story (1995)': 2.824,
 '780: Independence Day (ID4) (1996)': 2.769,
 '356: Forrest Gump (1994)': 2.7,
 '1259: Stand by Me (1986)': 2.636,
 '2916: Total Recall (1990)': 1.917}

# Popularity calculation

Count the number of ratings for each movie, order with the most number of ratings first.

In [4]:
rating_count = dict(data.iloc[:,2:].count())

rating_count_sorted = {k: round(v, 3) for k, v in sorted(rating_count.items(),
                                                         key=lambda item: item[1],
                                                         reverse=True)}

pprint(rating_count_sorted, sort_dicts=False)

{'1: Toy Story (1995)': 17,
 '593: Silence of the Lambs, The (1991)': 16,
 '260: Star Wars: Episode IV - A New Hope (1977)': 15,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 14,
 '780: Independence Day (ID4) (1996)': 13,
 '3578: Gladiator (2000)': 12,
 '2916: Total Recall (1990)': 12,
 '1265: Groundhog Day (1993)': 12,
 '2571: Matrix, The (1999)': 12,
 "527: Schindler's List (1993)": 12,
 '2762: Sixth Sense, The (1999)': 12,
 '2028: Saving Private Ryan (1998)': 11,
 '296: Pulp Fiction (1994)': 11,
 '1259: Stand by Me (1986)': 11,
 '2396: Shakespeare in Love (1998)': 11,
 '1198: Raiders of the Lost Ark (1981)': 11,
 '356: Forrest Gump (1994)': 10,
 '318: Shawshank Redemption, The (1994)': 10,
 '34: Babe (1995)': 10,
 '541: Blade Runner (1982)': 9}

# % of ratings 4+ (liking)

Calculate the percentage of ratings for each movie that are 4 or higher.

In [5]:
percentage_liked = {}

for column in data.columns[2:]:
    
    total = 0
    liked = 0
    
    for rate in data[column]:
        if rate == rate:
            total += 1
        if rate >= 4.0:
            liked += 1
            
    percentage_liked[column] = round(liked / total, 3)
        
percentage_liked_sorted = {k: round(v, 3) for k, v in sorted(percentage_liked.items(),
                                                             key=lambda item: item[1],
                                                             reverse=True)}

pprint(percentage_liked_sorted, sort_dicts=False)

{'318: Shawshank Redemption, The (1994)': 0.7,
 '260: Star Wars: Episode IV - A New Hope (1977)': 0.533,
 '3578: Gladiator (2000)': 0.5,
 '541: Blade Runner (1982)': 0.444,
 '593: Silence of the Lambs, The (1991)': 0.438,
 '1265: Groundhog Day (1993)': 0.417,
 '2571: Matrix, The (1999)': 0.417,
 '34: Babe (1995)': 0.4,
 '2028: Saving Private Ryan (1998)': 0.364,
 '296: Pulp Fiction (1994)': 0.364,
 '1259: Stand by Me (1986)': 0.364,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 0.357,
 '1: Toy Story (1995)': 0.353,
 "527: Schindler's List (1993)": 0.333,
 '2762: Sixth Sense, The (1999)': 0.333,
 '780: Independence Day (ID4) (1996)': 0.308,
 '356: Forrest Gump (1994)': 0.3,
 '2396: Shakespeare in Love (1998)': 0.273,
 '1198: Raiders of the Lost Ark (1981)': 0.273,
 '2916: Total Recall (1990)': 0.083}

# Top movies for someone who has seen 

Calculate movies that most often occur with Toy Story, using the $\frac{x+y}{x}$ method.

In other words, for each movie, calculate the percentage of Toy Story raters who also rated that movie. Order with the highest percentage first.

In [6]:
def association(movie1, movie2):
    total = 0
    sum_both = 0
    for rate1, rate2 in zip(data[movie1], data[movie2]):
        if rate1 == rate1:
            total += 1
        if rate1 == rate1 and rate2 == rate2:
            sum_both += 1
    return round(sum_both / total, 3)

In [7]:
movie_to_find_assosiations = '1: Toy Story (1995)'

associations = {}
for movie in data.columns[2:]:
    associations[movie] = association(movie_to_find_assosiations,
                                      movie)
    

associations_sorted = {k: round(v, 3) for k, v in sorted(associations.items(),
                                                         key=lambda item: item[1],
                                                         reverse=True)}

pprint(associations_sorted, sort_dicts=False)

{'1: Toy Story (1995)': 1.0,
 '260: Star Wars: Episode IV - A New Hope (1977)': 0.824,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 0.765,
 '593: Silence of the Lambs, The (1991)': 0.765,
 '780: Independence Day (ID4) (1996)': 0.765,
 '2916: Total Recall (1990)': 0.647,
 '1265: Groundhog Day (1993)': 0.647,
 '296: Pulp Fiction (1994)': 0.588,
 "527: Schindler's List (1993)": 0.588,
 '2762: Sixth Sense, The (1999)': 0.588,
 '3578: Gladiator (2000)': 0.529,
 '1259: Stand by Me (1986)': 0.529,
 '2571: Matrix, The (1999)': 0.529,
 '1198: Raiders of the Lost Ark (1981)': 0.529,
 '318: Shawshank Redemption, The (1994)': 0.471,
 '2028: Saving Private Ryan (1998)': 0.471,
 '2396: Shakespeare in Love (1998)': 0.471,
 '34: Babe (1995)': 0.471,
 '356: Forrest Gump (1994)': 0.412,
 '541: Blade Runner (1982)': 0.412}

# Correlation

Calculate the correlation between the vectors of ratings for Toy Story and each other movie.

In [8]:
movie_to_find_correlations = '1: Toy Story (1995)'
correlation = dict(data.iloc[:,2:].corr()[movie_to_find_correlations])

correlation_sorted = {k: round(v, 3) for k, v in sorted(correlation.items(),
                                                 key=lambda item: item[1],
                                                 reverse=True)}

pprint(correlation_sorted, sort_dicts=False)

{'1: Toy Story (1995)': 1.0,
 '318: Shawshank Redemption, The (1994)': 0.889,
 '34: Babe (1995)': 0.811,
 '296: Pulp Fiction (1994)': 0.71,
 '2028: Saving Private Ryan (1998)': 0.597,
 '356: Forrest Gump (1994)': 0.523,
 '541: Blade Runner (1982)': 0.33,
 '3578: Gladiator (2000)': 0.253,
 '2916: Total Recall (1990)': 0.164,
 '2396: Shakespeare in Love (1998)': 0.102,
 '1265: Groundhog Day (1993)': -0.063,
 '780: Independence Day (ID4) (1996)': -0.07,
 '260: Star Wars: Episode IV - A New Hope (1977)': -0.119,
 "527: Schindler's List (1993)": -0.22,
 '2762: Sixth Sense, The (1999)': -0.246,
 '1198: Raiders of the Lost Ark (1981)': -0.309,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': -0.315,
 '593: Silence of the Lambs, The (1991)': -0.568,
 '1259: Stand by Me (1986)': -0.61,
 '2571: Matrix, The (1999)': -0.722}

# Gender differences

In [9]:
data_male   = data[data["Gender (1 =F, 0=M)"] == 0]
data_female = data[data["Gender (1 =F, 0=M)"] == 1]


rating_count_male = dict(data_male.iloc[:,2:].mean())
rating_count_male_sorted = {k: round(v, 3) for k, v in sorted(rating_count_male.items(),
                                                              key=lambda item: item[1],
                                                              reverse=True)}

male_mean = round(np.average(list(rating_count_male.values())), 5)
print("male:")
pprint(rating_count_male_sorted, sort_dicts=False)
print(f"\naverage male rating: {male_mean}")

print("\n-------------------------\n")
rating_count_female = dict(data_female.iloc[:,2:].mean())
rating_count_female_sorted = {k: round(v, 3) for k, v in sorted(rating_count_female.items(),
                                                              key=lambda item: item[1],
                                                              reverse=True)}
female_mean = round(np.average(list(rating_count_female.values())), 5)
print("female:")
pprint(rating_count_female_sorted, sort_dicts=False)
print(f"\naverage female rating: {female_mean}")

male_female_diff = {}

for movie in rating_count_male.keys():
    male_female_diff[movie] = rating_count_male[movie] - rating_count_female[movie]
        
male_female_diff_sorted = {k: round(v, 3) for k, v in sorted(male_female_diff.items(),
                                                              key=lambda item: item[1],
                                                              reverse=True)}
print("\n-------------------------\n")
print("male - female:")
pprint(male_female_diff_sorted, sort_dicts=False)

female_male_diff = {}

for movie in rating_count_female.keys():
    female_male_diff[movie] = rating_count_female[movie] - rating_count_male[movie]
    
female_male_diff_sorted = {k: round(v, 3) for k, v in sorted(female_male_diff.items(),
                                                              key=lambda item: item[1],
                                                              reverse=True)}
print("\n-------------------------\n")
print("female - male:")
pprint(female_male_diff_sorted, sort_dicts=False)

print("\n-------------------------\n")
print(f"difference between mean ratings: {round(female_mean - male_mean, 3)}")

male:
{'1198: Raiders of the Lost Ark (1981)': 3.667,
 '1265: Groundhog Day (1993)': 3.5,
 "527: Schindler's List (1993)": 3.5,
 '318: Shawshank Redemption, The (1994)': 3.4,
 '593: Silence of the Lambs, The (1991)': 3.333,
 '2028: Saving Private Ryan (1998)': 3.143,
 '2571: Matrix, The (1999)': 3.143,
 '260: Star Wars: Episode IV - A New Hope (1977)': 3.125,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 3.0,
 '1259: Stand by Me (1986)': 3.0,
 '541: Blade Runner (1982)': 3.0,
 '780: Independence Day (ID4) (1996)': 2.857,
 '3578: Gladiator (2000)': 2.833,
 '2762: Sixth Sense, The (1999)': 2.667,
 '296: Pulp Fiction (1994)': 2.625,
 '1: Toy Story (1995)': 2.3,
 '356: Forrest Gump (1994)': 2.25,
 '2916: Total Recall (1990)': 2.2,
 '2396: Shakespeare in Love (1998)': 2.143,
 '34: Babe (1995)': 2.0}

average male rating: 2.88429

-------------------------

female:
{'2396: Shakespeare in Love (1998)': 4.25,
 '296: Pulp Fiction (1994)': 4.0,
 '318: Shawshank Redemption, The (1994)': 3.8,
 '1: Toy Story (1995)': 3.571,
 '541: Blade Runner (1982)': 3.5,
 '260: Star Wars: Episode IV - A New Hope (1977)': 3.429,
 '34: Babe (1995)': 3.429,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 3.0,
 '356: Forrest Gump (1994)': 3.0,
 '3578: Gladiator (2000)': 3.0,
 '2762: Sixth Sense, The (1999)': 3.0,
 '1265: Groundhog Day (1993)': 2.833,
 '2028: Saving Private Ryan (1998)': 2.75,
 '593: Silence of the Lambs, The (1991)': 2.714,
 '780: Independence Day (ID4) (1996)': 2.667,
 "527: Schindler's List (1993)": 2.5,
 '1259: Stand by Me (1986)': 2.429,
 '2571: Matrix, The (1999)': 2.4,
 '1198: Raiders of the Lost Ark (1981)': 2.0,
 '2916: Total Recall (1990)': 1.714}

average female rating: 2.99929

-------------------------

male - female:
{'1198: Raiders of the Lost Ark (1981)': 1.667,
 "527: Schindler's List (1993)": 1.0,
 '2571: Matrix, The (1999)': 0.743,
 '1265: Groundhog Day (1993)': 0.667,
 '593: Silence of the Lambs, The (1991)': 0.619,
 '1259: Stand by Me (1986)': 0.571,
 '2916: Total Recall (1990)': 0.486,
 '2028: Saving Private Ryan (1998)': 0.393,
 '780: Independence Day (ID4) (1996)': 0.19,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 0.0,
 '3578: Gladiator (2000)': -0.167,
 '260: Star Wars: Episode IV - A New Hope (1977)': -0.304,
 '2762: Sixth Sense, The (1999)': -0.333,
 '318: Shawshank Redemption, The (1994)': -0.4,
 '541: Blade Runner (1982)': -0.5,
 '356: Forrest Gump (1994)': -0.75,
 '1: Toy Story (1995)': -1.271,
 '296: Pulp Fiction (1994)': -1.375,
 '34: Babe (1995)': -1.429,
 '2396: Shakespeare in Love (1998)': -2.107}

-------------------------

female - male:
{'2396: Shakespeare in Love (1998)': 2.107,
 '34: Babe (1995)': 1.429,
 '296: Pulp Fiction (1994)': 1.375,
 '1: Toy Story (1995)': 1.271,
 '356: Forrest Gump (1994)': 0.75,
 '541: Blade Runner (1982)': 0.5,
 '318: Shawshank Redemption, The (1994)': 0.4,
 '2762: Sixth Sense, The (1999)': 0.333,
 '260: Star Wars: Episode IV - A New Hope (1977)': 0.304,
 '3578: Gladiator (2000)': 0.167,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 0.0,
 '780: Independence Day (ID4) (1996)': -0.19,
 '2028: Saving Private Ryan (1998)': -0.393,
 '2916: Total Recall (1990)': -0.486,
 '1259: Stand by Me (1986)': -0.571,
 '593: Silence of the Lambs, The (1991)': -0.619,
 '1265: Groundhog Day (1993)': -0.667,
 '2571: Matrix, The (1999)': -0.743,
 "527: Schindler's List (1993)": -1.0,
 '1198: Raiders of the Lost Ark (1981)': -1.667}

-------------------------

difference between mean ratings: 0.115

# % of ratings 4+ (liking), gender

Calculate the percentage of ratings for each movie that are 4 or higher separately for males and females.

In [10]:
percentage_liked_male = {}

for column in data_male.columns[2:]:
    
    total = 0
    liked_male = 0
    
    for rate in data_male[column]:
        if rate == rate:
            total += 1
        if rate >= 4.0:
            liked_male += 1
            
    percentage_liked_male[column] = round(liked_male / total, 3)
        
percentage_liked_male_sorted = {k: round(v, 3) for k, v in sorted(percentage_liked_male.items(),
                                                             key=lambda item: item[1],
                                                             reverse=True)}

pprint(percentage_liked_male_sorted, sort_dicts=False)
male_mean = round(np.mean(list(percentage_liked_male_sorted.values())), 5)
print("male:")
print(f"\naverage male rating: {male_mean}")
print("\n-------------------------\n")



percentage_liked_female = {}

for column in data_female.columns[2:]:
    
    total = 0
    liked_female = 0
    
    for rate in data_female[column]:
        if rate == rate:
            total += 1
        if rate >= 4.0:
            liked_female += 1
            
    percentage_liked_female[column] = round(liked_female / total, 3)
        
percentage_liked_female_sorted = {k: round(v, 3) for k, v in sorted(percentage_liked_female.items(),
                                                             key=lambda item: item[1],
                                                             reverse=True)}

pprint(percentage_liked_female_sorted, sort_dicts=False)
female_mean = round(np.average(list(percentage_liked_female_sorted.values())), 5)
print("female:")
print(f"\naverage female rating: {female_mean}")
print("\n-------------------------\n")


male_female_diff = {}

for movie in percentage_liked_male.keys():
    male_female_diff[movie] = percentage_liked_male[movie] - percentage_liked_female[movie]
        
male_female_diff_sorted = {k: round(v, 3) for k, v in sorted(male_female_diff.items(),
                                                              key=lambda item: item[1],
                                                              reverse=True)}
print("\n-------------------------\n")
print("male - female:")
pprint(male_female_diff_sorted, sort_dicts=False)

female_male_diff = {}

for movie in percentage_liked_female.keys():
    female_male_diff[movie] = percentage_liked_female[movie] - percentage_liked_male[movie]
    
female_male_diff_sorted = {k: round(v, 3) for k, v in sorted(female_male_diff.items(),
                                                              key=lambda item: item[1],
                                                              reverse=True)}
print("\n-------------------------\n")
print("female - male:")
pprint(female_male_diff_sorted, sort_dicts=False)

{'318: Shawshank Redemption, The (1994)': 0.6,
 '2571: Matrix, The (1999)': 0.571,
 '593: Silence of the Lambs, The (1991)': 0.556,
 '260: Star Wars: Episode IV - A New Hope (1977)': 0.5,
 '3578: Gladiator (2000)': 0.5,
 '1265: Groundhog Day (1993)': 0.5,
 "527: Schindler's List (1993)": 0.5,
 '1198: Raiders of the Lost Ark (1981)': 0.5,
 '2762: Sixth Sense, The (1999)': 0.333,
 '2028: Saving Private Ryan (1998)': 0.286,
 '780: Independence Day (ID4) (1996)': 0.286,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 0.25,
 '296: Pulp Fiction (1994)': 0.25,
 '1259: Stand by Me (1986)': 0.25,
 '1: Toy Story (1995)': 0.2,
 '2916: Total Recall (1990)': 0.2,
 '541: Blade Runner (1982)': 0.2,
 '356: Forrest Gump (1994)': 0.0,
 '2396: Shakespeare in Love (1998)': 0.0,
 '34: Babe (1995)': 0.0}
male:

average male rating: 0.3241

-------------------------

{'318: Shawshank Redemption, The (1994)': 0.8,
 '2396: Shakespeare in Love (1998)': 0.75,
 '541: Blade Runner (1982)': 0.75,
 '296: Pulp Fiction (1994)': 0.667,
 '260: Star Wars: Episode IV - A New Hope (1977)': 0.571,
 '1: Toy Story (1995)': 0.571,
 '34: Babe (1995)': 0.571,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 0.5,
 '356: Forrest Gump (1994)': 0.5,
 '3578: Gladiator (2000)': 0.5,
 '2028: Saving Private Ryan (1998)': 0.5,
 '1259: Stand by Me (1986)': 0.429,
 '780: Independence Day (ID4) (1996)': 0.333,
 '1265: Groundhog Day (1993)': 0.333,
 '2762: Sixth Sense, The (1999)': 0.333,
 '593: Silence of the Lambs, The (1991)': 0.286,
 '2571: Matrix, The (1999)': 0.2,
 "527: Schindler's List (1993)": 0.167,
 '2916: Total Recall (1990)': 0.0,
 '1198: Raiders of the Lost Ark (1981)': 0.0}
female:

average female rating: 0.43805

-------------------------


-------------------------

male - female:
{'1198: Raiders of the Lost Ark (1981)': 0.5,
 '2571: Matrix, The (1999)': 0.371,
 "527: Schindler's List (1993)": 0.333,
 '593: Silence of the Lambs, The (1991)': 0.27,
 '2916: Total Recall (1990)': 0.2,
 '1265: Groundhog Day (1993)': 0.167,
 '3578: Gladiator (2000)': 0.0,
 '2762: Sixth Sense, The (1999)': 0.0,
 '780: Independence Day (ID4) (1996)': -0.047,
 '260: Star Wars: Episode IV - A New Hope (1977)': -0.071,
 '1259: Stand by Me (1986)': -0.179,
 '318: Shawshank Redemption, The (1994)': -0.2,
 '2028: Saving Private Ryan (1998)': -0.214,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': -0.25,
 '1: Toy Story (1995)': -0.371,
 '296: Pulp Fiction (1994)': -0.417,
 '356: Forrest Gump (1994)': -0.5,
 '541: Blade Runner (1982)': -0.55,
 '34: Babe (1995)': -0.571,
 '2396: Shakespeare in Love (1998)': -0.75}

-------------------------

female - male:
{'2396: Shakespeare in Love (1998)': 0.75,
 '34: Babe (1995)': 0.571,
 '541: Blade Runner (1982)': 0.55,
 '356: Forrest Gump (1994)': 0.5,
 '296: Pulp Fiction (1994)': 0.417,
 '1: Toy Story (1995)': 0.371,
 '1210: Star Wars: Episode VI - Return of the Jedi (1983)': 0.25,
 '2028: Saving Private Ryan (1998)': 0.214,
 '318: Shawshank Redemption, The (1994)': 0.2,
 '1259: Stand by Me (1986)': 0.179,
 '260: Star Wars: Episode IV - A New Hope (1977)': 0.071,
 '780: Independence Day (ID4) (1996)': 0.047,
 '3578: Gladiator (2000)': 0.0,
 '2762: Sixth Sense, The (1999)': 0.0,
 '1265: Groundhog Day (1993)': -0.167,
 '2916: Total Recall (1990)': -0.2,
 '593: Silence of the Lambs, The (1991)': -0.27,
 "527: Schindler's List (1993)": -0.333,
 '2571: Matrix, The (1999)': -0.371,
 '1198: Raiders of the Lost Ark (1981)': -0.5}